---
title: "Geo200cn_lab8_YOSE"
author: "Jenny Cribbs"
date: "2024-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r}
library(sf)
library(terra)
library(tmap)
library(tidyverse)
library(RColorBrewer)
library(maptiles)
library(cartogram)
```
## Vector Data

```{r}
# get example shapefile of luxembourg
filename <- system.file("ex/lux.shp", package="terra")
filename
# bring object into R
lux <- vect(filename)
# check data type
class(lux)
# map using the geometry 
plot(lux)
# map attributes
plot(lux, 'AREA')
plot(lux, 'NAME_2')
```
```{r}
# convert to a dataframe
d <- as.data.frame(lux)
head(d)
```

```{r}
# look at a single variable (select and tidy functions don't work)
lux$NAME_2
```

```{r}
# create a new variable
lux$AREA_100 <- lux$AREA * 100
lux$AREA_100

# subsetting to create a vector with only one variable
lux[, 'NAME_2']

# select and plot one row
g <- lux[lux$NAME_1 == 'Grevenmacher',]
plot(g)
```
## Raster Data

```{r}
# create a raster from scratch
r <- rast(ncol = 10, nrow = 10, xmin = -150, xmax = -80, ymin = 20, ymax = 60)
r
# no values associated with raster cells
hasValues(r)

# assign random values to the raster cells
values(r) <- runif(ncell(r))
r

# assign sequential numbers to the raster cells
values(r) <- 1:ncell(r)
r
```
```{r}
plot(r)
```
```{r}
# create a multi-layer object
r2 <- r * r
r3 <- sqrt(r)
s <- c(r, r2, r3)
s
plot(s)
```
## Bringing in Raster Data from files
```{r}
# get example data from terra
filename <- system.file("ex/elev.tif", package = "terra")
basename(filename)

# bring data into r
elev <- rast(filename)
elev
plot(elev)
```
```{r}
# convert lux vector to a raster to use as a mask
r <- rast(lux, ncols=75, nrows=100)
plot(r) # blank because there are no values associated with r yet
```
```{r}
# transfer values from the lux vector object to the raster cells with rasterize
vr <- rasterize(lux, r, 'AREA')
plot(vr)
```

