---
title: "Yosemite WPBR Prelim"
author: "Jenny Cribbs"
date: "2023-10-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in Data


```{r}
if (!require("librarian")) install.packages("librarian")
librarian::shelf(tidyverse, readxl, viridis, patchwork)

theme_set(
  theme_bw(base_size = 17)+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
)

## unzipping files on your computer
setwd("/Users/jennifercribbs/Documents/YOSE/Analysis/Test")
files <- list.files()
outdir <- "/Users/jennifercribbs/Documents/YOSE/Analysis/Test"

## for loop to unzip files on your computer
# for (file in files) {
#   unzip(paste0(outdir,"/", file))
# }


## reading in all data
folders <- list.dirs(outdir)[-c(1,4)]

tree_list <- data.frame()

for (folder in folders) {
  newfiles = list.files(folder, pattern = "PILAdata")
  for(file in newfiles) {
    xlsfile <- read_excel(paste0(folder,"/",file)) %>% 
      dplyr::select(plotID, plot_type, slope, aspect, plot_elevation_ft, fireseverity_50m, fireseverity_100m, fireseverity_150m, fireseverity_200m, ribes_50m, ribes_100m, ribes_150m, ribes_200m, 
                    treeNum, DBH_cm, height_m, pitchTubes, exitHoles, activeBranchCanker, inactiveBranchCanker, 
                    activeBoleCanker, inactiveBoleCanker, DTOP, flags, percentLive, damageCodes, notes, plot_elevation_ft)
    tree_list <- rbind(tree_list, xlsfile)
  }
}


## summarizing data

# change data type to numeric 
tree_list$activeBoleCanker <- as.numeric(tree_list$activeBoleCanker) 
tree_list$inactiveBoleCanker <- as.numeric(tree_list$inactiveBoleCanker)
tree_list$activeBranchCanker <- as.numeric(tree_list$activeBranchCanker)
tree_list$inactiveBranchCanker <- as.numeric(tree_list$inactiveBranchCanker)
tree_list$plot_elevation_ft <- as.numeric(tree_list$plot_elevation_ft)

# create new columns combining active and inactive bole and branch cankers 
pila <- tree_list %>% 
  mutate(bole_canker = activeBoleCanker + inactiveBoleCanker,
         branch_canker = activeBranchCanker + inactiveBranchCanker) %>% 
  mutate(infected = ifelse(bole_canker|branch_canker>0,1,0))
```
```{r}
# create a new column for WPBR incidence based on any branch or bole cankers
pila <- pila %>% mutate(wpbr = if_else (inactiveBranchCanker > 0 | activeBranchCanker > 0 | inactiveBoleCanker > 0 | activeBoleCanker > 0, 1, 0))

# create a new column for size class 
pila <- pila %>% mutate(size_class = case_when (DBH_cm <5 ~ "sapling", DBH_cm >= 5 & DBH_cm < 50 ~ "small", DBH_cm >= 50 & DBH_cm < 100 ~ "medium", DBH_cm >= 100 ~ "large"))

#pila %>% summarize (n=n())

hist(pila$wpbr)

# add up the total number of trees
totTrees <- nrow(pila)

# calculate incidence of wpbr relative to all trees assessed 
incidence = (sum(pila$wpbr, na.rm = T)) / totTrees * 100

# plot level incidence
sum(unique(pila$plotID), na.rm = T)
# count(unique(pila$YPE_plot))

# put unique values of plot into a vector
plots <- unique(pila$plot)

# for each plot calculate tree level incidence 

pila %>% group_by(pila$plotID) %>% 
    summarise(plotIncidence = (sum(wpbr) / length(unique(treeNum, na.rm=T)) * 100))

#summarize(numtrees = length(unique(treeNum, na.rm=T)), suminf = sum(infected),
            #per_infected = (suminf/numtrees)*100) 
length(unique(pila$treeNum, na.rm=T))
unique(pila$treeNum)


# relationship between size and wpbr
class(pila$DBH_cm)
class(pila$wpbr)
pila$wpbr <- as.numeric(pila$wpbr, na.rm = T)
pila$DBH_cm <- as.numeric(pila$DBH_cm, na.rm = T) 
boxplot(pila$wpbr, pila$DBH_cm, xlab = "WPBR status", ylab = "DBH")
plot(pila$DBH_cm, pila$height_m, pch = 16, col = pila$wpbr)
class(pila$wpbr)

theme_set(
  theme_bw(base_size = 12)+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
)
#pila$wpbr <- pila %>% mutate(as.factor(wpbr))
pila <- pila %>% factor(pila$size_class, levels = levels(size_class)[1,2,3,4,5], ordered = TRUE) 

ggplot(pila, aes(x=size_class, y=totalcankers, color = size_class)) + geom_violin() +
  #geom_boxplot(width=0.1) + theme_minimal() +
  ggtitle("WPBR Infection Rate is Highest for Small Trees") + 
  xlab("Tree Size Class") + ylab("Total Canker Score") +
  scale_x_discrete(limits=c("sapling", "small", "medium", "large"))
```

```{r}
# severity according to Duriscoe & Duriscoe 2002
pila <- pila %>% 
  mutate (cs = 
            case_when(activeBoleCanker > 0 | inactiveBoleCanker > 0 ~ 5, 
                      activeBoleCanker == 0 & inactiveBoleCanker == 0 & activeBranchCanker == 0 & inactiveBranchCanker == 0 ~ 0,
                      activeBranchCanker > 0 & activeBranchCanker <= 3 | inactiveBranchCanker > 0 & inactiveBranchCanker <= 3 ~ 1,
                      activeBranchCanker > 3 & activeBranchCanker <= 9 | inactiveBranchCanker > 3 & inactiveBranchCanker <= 9 ~ 2,
                      activeBranchCanker > 9 & activeBranchCanker <= 25 | inactiveBranchCanker > 9 & inactiveBranchCanker <= 25 ~ 3,
                      activeBranchCanker > 25 | inactiveBranchCanker > 25 ~ 4)
          )
# distribution of canker severity
hist(pila$cs) # may want to adapt this to YOSE

# calculate severity
# 25in = 63.5cm  
class(pila$DBH_cm)
pila <- pila %>% mutate(severity = 
                          case_when(cs == 0 ~ 0, 
                                cs > 0 & DBH_cm <= 63.5 ~ cs + (63.5 - as.numeric(DBH_cm) / 5),
                                cs > 0 & DBH_cm > 63.5 ~ cs + ((63.5 - 63.5) / 5)
                                    )
                          )
  
hist(pila$severity, xlab = "Severity", main = "Histogram of WPBR Severity")

# maybe do not lump since there are so few trees with many cankers?
# Should active branch cankers be weighted higher than inactive?

pila <- pila %>% 
  mutate (cs = 
            case_when(activeBoleCanker > 0 | inactiveBoleCanker > 0 ~ 5, 
                      activeBoleCanker == 0 & inactiveBoleCanker == 0 & activeBranchCanker == 0 & inactiveBranchCanker == 0 ~ 0,
                      activeBranchCanker > 0 & activeBranchCanker <= 3 | inactiveBranchCanker > 0 & inactiveBranchCanker <= 3 ~ 1,
                      activeBranchCanker > 3 & activeBranchCanker <= 9 | inactiveBranchCanker > 3 & inactiveBranchCanker <= 9 ~ 2
                      )
          )

severityHist <- hist(pila$severity, xlab = "Severity", main = "Histogram of WPBR Severity")

IRhist <- hist(summarydat$per_infected, xlab = "WPBR Extent", "Historgram of WPBR Extent")

severityHist + IRhist

# Total Cankers rather than severity
pila <- pila %>% mutate (totalcankers = (activeBranchCanker + inactiveBranchCanker) + (activeBoleCanker + inactiveBoleCanker)
```

